In [52]:
import pandas as pd

In [53]:
df = pd.read_csv('zomato_cleaned.csv')

In [54]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,...,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,10.280582,Slow
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,...,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,6.242319,Average
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,...,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,13.787860,Average
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,...,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2.930258,Average
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,...,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.396618,Slow

In [55]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)',
       'distance_km', 'delivery_speed'],
      dtype='str')

In [56]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,...,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,10.280582,Slow
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,...,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,6.242319,Average
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,...,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,13.787860,Average
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,...,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2.930258,Average
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,...,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.396618,Slow

In [57]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)',
       'distance_km', 'delivery_speed'],
      dtype='str')

In [58]:
print(df.shape)
print(df.isnull().sum())
print(df['Delivery_person_ID'].nunique())

(38964, 22)
ID                                0
Delivery_person_ID                0
Delivery_person_Age            1019
Delivery_person_Ratings        1055
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                     835
Time_Order_picked                 0
Weather_conditions                0
Road_traffic_density              0
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries               0
Festival                          0
City                              0
Time_taken (min)                  0
distance_km                       0
delivery_speed                    0
dtype: int64
1170

In [59]:
print(df['Weather_conditions'].unique())
print(df['Road_traffic_density'].unique())
print(df['City'].unique())
print(df['Festival'].unique())

<StringArray>
['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny']
Length: 6, dtype: str
<StringArray>
['Jam', 'High', 'Medium', 'Low']
Length: 4, dtype: str
<StringArray>
['Metropolitian', 'Urban', 'Semi-Urban']
Length: 3, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [60]:
dp = df.drop(columns = ['Restaurant_latitude', 'Restaurant_longitude', 'Delivery_location_latitude',
                        'Delivery_location_longitude', 'Order_Date', 'Time_Orderd'])

In [64]:
dp = df.groupby('Delivery_person_ID')

In [62]:
dp.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
0,0xcdcd,DEHRES17DEL01,36.0,4.2,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,10.280582,Slow
1,0xd987,KOCRES16DEL01,21.0,4.7,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,6.242319,Average
2,0x2784,PUNERES13DEL03,23.0,4.7,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,13.787860,Average
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,2.930258,Average
4,0xdb64,KNPRES14DEL02,24.0,4.7,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,19.396618,Slow

In [65]:
dp.ngroups

1170

In [68]:
dp.first()

,ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),distance_km,delivery_speed
Delivery_person_ID,,,,,,,,,,,,,,,,,,,,,
AGRRES010DEL01,0xdebb,38.0,4.7,27.163303,78.057044,27.233303,78.127044,18-02-2022,22:45,22:50,...,Low,1,Buffet,motorcycle,1.0,No,Urban,28,10.416964,Average
AGRRES010DEL02,0xd3bc,37.0,4.4,27.163303,78.057044,27.243303,78.137044,18-02-2022,0.916666667,22:10,...,Jam,0,Drinks,motorcycle,1.0,No,Metropolitian,39,11.904865,Slow
AGRRES010DEL03,0xe1b4,38.0,4.5,27.163303,78.057044,27.253303,78.147044,12-02-2022,0.875,21:10,...,Jam,1,Snack,motorcycle,2.0,No,Metropolitian,38,13.392708,Slow
AGRRES01DEL01,0xc371,34.0,4.8,27.161661,78.011544,27.231661,78.081544,12-02-2022,21:50,23:05,...,Low,1,Meal,motorcycle,1.0,No,Urban,12,10.417032,Fast
AGRRES01DEL02,0xd6ef,24.0,4.4,27.161661,78.011544,27.241661,78.091544,18-02-2022,20:45,0.875,...,Jam,2,Meal,scooter,0.0,No,Metropolitian,40,11.904943,Slow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VADRES19DEL02,0x5e14,38.0,4.3,22.311844,73.165081,22.441844,73.295081,25-03-2022,21:25,21:35,...,Jam,2,Buffet,electric_scooter,1.0,Yes,Metropolitian,48,19.688309,Slow
VADRES19DEL03,0x6932,29.0,5.0,22.311844,73.165081,22.341844,73.195081,19-03-2022,20:40,20:55,...,Jam,0,Snack,motorcycle,1.0,No,Urban,20,4.544208,Average
VADRES20DEL01,0x2dc6,34.0,4.7,22.311358,73.164798,22.351358,73.204798,19-03-2022,12:35,12:45,...,High,2,Drinks,electric_scooter,1.0,No,Metropolitian,28,6.058854,Average
VADRES20DEL02,0xbaa4,36.0,4.8,22.311358,73.164798,22.331358,73.184798,05-04-2022,08:50,09:05,...,Low,1,Buffet,motorcycle,0.0,No,Metropolitian,29,3.029527,Average
VADRES20DEL03,0x95b6,35.0,4.8,22.311358,73.164798,22.371358,73.224798,13-03-2022,19:10,19:20,...,Jam,1,Drinks,motorcycle,1.0,No,Metropolitian,30,9.087980,Average

In [70]:
#an avg delivery person's avgs hehe

dp = df.groupby('Delivery_person_ID').agg(
    orders_completed = ('ID', 'count'),
    avg_deliverer_rating = ('Delivery_person_Ratings', 'mean'),
    avg_delivery_time = ('Time_taken (min)', 'mean')
).reset_index().round(2)

In [71]:
df['distance_km'].value_counts().sort_index()

distance_km
1.465067     3
1.465123     4
1.465140     2
1.465159     4
1.465161     3
            ..
20.968993    2
20.968994    4
20.969028    2
20.969045    3
20.969489    3
Name: count, Length: 4352, dtype: int64

In [72]:
dp

,Delivery_person_ID,orders_completed,avg_deliverer_rating,avg_delivery_time
0,AGRRES010DEL01,13,4.77,25.23
1,AGRRES010DEL02,14,4.67,28.36
2,AGRRES010DEL03,12,4.58,28.42
3,AGRRES01DEL01,10,4.52,27.10
4,AGRRES01DEL02,14,4.70,24.43
...,...,...,...,...
1165,VADRES19DEL02,55,4.63,26.64
1166,VADRES19DEL03,39,4.67,26.26
1167,VADRES20DEL01,56,4.62,27.48
1168,VADRES20DEL02,46,4.59,25.74
1169,VADRES20DEL03,36,4.68,26.19

In [73]:
# performance in weather

weather_performance = df.groupby(['Delivery_person_ID', 'Weather_conditions']).agg(avg_time = ('Time_taken (min)', 'mean')).reset_index().round(2)

In [74]:
weather_performance

     Delivery_person_ID Weather_conditions  avg_time
0        AGRRES010DEL01             Cloudy     25.20
1        AGRRES010DEL01                Fog     23.00
2        AGRRES010DEL01         Sandstorms     27.00
3        AGRRES010DEL01             Stormy     28.00
4        AGRRES010DEL01              Sunny     23.00
...                 ...                ...       ...
6604      VADRES20DEL03                Fog     30.83
6605      VADRES20DEL03         Sandstorms     24.64
6606      VADRES20DEL03             Stormy     24.50
6607      VADRES20DEL03              Sunny     22.25
6608      VADRES20DEL03              Windy     29.40

[6609 rows x 3 columns]

In [75]:
traffic_performance = df.groupby(['Delivery_person_ID', 'Road_traffic_density']).agg(avg_time = ('Time_taken (min)', 'mean')).reset_index().round(2)

In [76]:
traffic_performance

     Delivery_person_ID Road_traffic_density  avg_time
0        AGRRES010DEL01                 High     26.75
1        AGRRES010DEL01                  Low     23.67
2        AGRRES010DEL01               Medium     26.33
3        AGRRES010DEL02                 High     30.00
4        AGRRES010DEL02                  Jam     35.00
...                 ...                  ...       ...
4151      VADRES20DEL02                  Low     19.72
4152      VADRES20DEL02               Medium     29.09
4153      VADRES20DEL03                  Jam     29.38
4154      VADRES20DEL03                  Low     24.00
4155      VADRES20DEL03               Medium     23.30

[4156 rows x 3 columns]

In [77]:
#city type performance

city_performance = df.groupby(['Delivery_person_ID', 'City']).agg(avg_time = ('Time_taken (min)', 'mean')).reset_index().round(2)

In [78]:
city_performance

     Delivery_person_ID           City  avg_time
0        AGRRES010DEL01  Metropolitian     23.33
1        AGRRES010DEL01          Urban     29.50
2        AGRRES010DEL02  Metropolitian     29.00
3        AGRRES010DEL02          Urban     26.75
4        AGRRES010DEL03  Metropolitian     29.64
...                 ...            ...       ...
2439      VADRES20DEL01          Urban     21.00
2440      VADRES20DEL02  Metropolitian     27.43
2441      VADRES20DEL02          Urban     20.36
2442      VADRES20DEL03  Metropolitian     27.64
2443      VADRES20DEL03          Urban     21.12

[2444 rows x 3 columns]

In [79]:
#festival type performance

festival_performance = df.groupby(['Delivery_person_ID', 'Festival']).agg(avg_time = ('Time_taken (min)', 'mean')).reset_index().round(2)
festival_performance

     Delivery_person_ID Festival  avg_time
0        AGRRES010DEL01       No     25.23
1        AGRRES010DEL02       No     26.92
2        AGRRES010DEL02      Yes     47.00
3        AGRRES010DEL03       No     26.64
4        AGRRES010DEL03      Yes     48.00
...                 ...      ...       ...
1690      VADRES20DEL01       No     27.11
1691      VADRES20DEL01      Yes     48.00
1692      VADRES20DEL02       No     24.82
1693      VADRES20DEL02      Yes     46.00
1694      VADRES20DEL03       No     26.19

[1695 rows x 3 columns]

In [80]:
# performance in dst

distance_performance = df.groupby(['Delivery_person_ID', 'distance_km']).agg(avg_time = ('Time_taken (min)', 'mean')).reset_index().round(2)
distance_performance

     Delivery_person_ID  distance_km  avg_time
0        AGRRES010DEL01         1.49     23.00
1        AGRRES010DEL01         5.95     25.50
2        AGRRES010DEL01        10.42     25.50
3        AGRRES010DEL01        16.37     27.67
4        AGRRES010DEL02         2.98     22.75
...                 ...          ...       ...
4371      VADRES20DEL02        12.12     33.75
4372      VADRES20DEL02        19.69     25.50
4373      VADRES20DEL03         4.54     24.86
4374      VADRES20DEL03         9.09     23.30
4375      VADRES20DEL03        13.63     30.17

[4376 rows x 3 columns]

In [81]:
weather = 'Cloudy'
traffic = 'Jam'
festival = 'Yes'
city = 'Semi-Urban'

distance = 10.42

In [82]:
print(weather_performance.head())
print(traffic_performance.head())
print(festival_performance.head())
print(city_performance.head())
print(distance_performance.head())

  Delivery_person_ID Weather_conditions  avg_time
0     AGRRES010DEL01             Cloudy      25.2
1     AGRRES010DEL01                Fog      23.0
2     AGRRES010DEL01         Sandstorms      27.0
3     AGRRES010DEL01             Stormy      28.0
4     AGRRES010DEL01              Sunny      23.0
  Delivery_person_ID Road_traffic_density  avg_time
0     AGRRES010DEL01                 High     26.75
1     AGRRES010DEL01                  Low     23.67
2     AGRRES010DEL01               Medium     26.33
3     AGRRES010DEL02                 High     30.00
4     AGRRES010DEL02                  Jam     35.00
  Delivery_person_ID Festival  avg_time
0     AGRRES010DEL01       No     25.23
1     AGRRES010DEL02       No     26.92
2     AGRRES010DEL02      Yes     47.00
3     AGRRES010DEL03       No     26.64
4     AGRRES010DEL03      Yes     48.00
  Delivery_person_ID           City  avg_time
0     AGRRES010DEL01  Metropolitian     23.33
1     AGRRES010DEL01          Urban     29.50
2     AGRRES010DEL02  Metropolitian     29.00
3     AGRRES010DEL02          Urban     26.75
4     AGRRES010DEL03  Metropolitian     29.64
  Delivery_person_ID  distance_km  avg_time
0     AGRRES010DEL01         1.49     23.00
1     AGRRES010DEL01         5.95     25.50
2     AGRRES010DEL01        10.42     25.50
3     AGRRES010DEL01        16.37     27.67
4     AGRRES010DEL02         2.98     22.75

In [83]:
weather_score = weather_performance[
    weather_performance['Weather_conditions'] == weather
]
weather_score.head()

   Delivery_person_ID Weather_conditions  avg_time
0      AGRRES010DEL01             Cloudy      25.2
6      AGRRES010DEL02             Cloudy      18.0
12     AGRRES010DEL03             Cloudy      30.0
18      AGRRES01DEL01             Cloudy      17.0
24      AGRRES01DEL02             Cloudy      34.5

In [84]:
traffic_score = traffic_performance[
    traffic_performance['Road_traffic_density'] == traffic
]
traffic_score.head()

   Delivery_person_ID Road_traffic_density  avg_time
4      AGRRES010DEL02                  Jam     35.00
7      AGRRES010DEL03                  Jam     35.33
10      AGRRES01DEL01                  Jam     39.00
13      AGRRES01DEL02                  Jam     34.40
16      AGRRES01DEL03                  Jam     25.50

In [85]:
festival_score = festival_performance[
    festival_performance['Festival'] == festival
]
festival_score.head()

   Delivery_person_ID Festival  avg_time
2      AGRRES010DEL02      Yes      47.0
4      AGRRES010DEL03      Yes      48.0
9       AGRRES03DEL01      Yes      46.0
20      AGRRES07DEL02      Yes      42.0
28      AGRRES11DEL03      Yes      44.0

In [86]:
city_score = city_performance[
    city_performance['City'] == city
]
city_score.head()

    Delivery_person_ID        City  avg_time
63       AGRRES17DEL01  Semi-Urban      54.0
76       AGRRES20DEL01  Semi-Urban      50.0
115      ALHRES08DEL03  Semi-Urban      48.0
134      ALHRES15DEL01  Semi-Urban      49.0
262    BANGRES010DEL01  Semi-Urban      54.0

In [87]:
df['distance_class'] = pd.cut(
    df['distance_km'],
    bins=[0, 5, 10, 15, float('inf')],
    labels=['0-5', '5-10', '10-15', '15>']
)
print(df[['distance_km', 'distance_class']].head())

   distance_km distance_class
0    10.280582          10-15
1     6.242319           5-10
2    13.787860          10-15
3     2.930258            0-5
4    19.396618            15>

In [88]:
distance_performance = df.groupby(
    ['Delivery_person_ID', 'distance_class']
).agg(
    avg_time=('Time_taken (min)', 'mean')
).reset_index().round(2)

In [89]:
def get_distance_class(distance):
    if distance <= 5:
        return '0-5'
    elif distance <= 10:
        return '5-10'
    elif distance <= 15:
        return '10-15'
    else:
        return '15>'

In [90]:
distance = 6

In [91]:
distance_class = get_distance_class(distance)
distance_score = distance_performance[
    distance_performance['distance_class'] == distance_class
]
distance_score.head()

   Delivery_person_ID distance_class  avg_time
1      AGRRES010DEL01           5-10     25.50
5      AGRRES010DEL02           5-10     25.00
9      AGRRES010DEL03           5-10     19.00
13      AGRRES01DEL01           5-10     26.33
17      AGRRES01DEL02           5-10     21.33

In [92]:
distance_score.head()

   Delivery_person_ID distance_class  avg_time
1      AGRRES010DEL01           5-10     25.50
5      AGRRES010DEL02           5-10     25.00
9      AGRRES010DEL03           5-10     19.00
13      AGRRES01DEL01           5-10     26.33
17      AGRRES01DEL02           5-10     21.33

In [129]:
weather = 'Cloudy'
traffic = 'Low'
festival = 'No'
city = 'Urban'
distance = 3

In [130]:
weather_score = weather_performance[
    weather_performance['Weather_conditions'] == weather
]

traffic_score = traffic_performance[
    traffic_performance['Road_traffic_density'] == traffic
]

festival_score = festival_performance[
    festival_performance['Festival'] == festival
]

city_score = city_performance[
    city_performance['City'] == city
]

distance_class = get_distance_class(distance)

distance_score = distance_performance[
    distance_performance['distance_class'] == distance_class
]

In [131]:
weather_score = weather_score.rename(
    columns = {'avg_time' : 'weather_avg_time'}
)
traffic_score = traffic_score.rename(columns={'avg_time': 'traffic_avg_time'})
festival_score = festival_score.rename(columns={'avg_time': 'festival_avg_time'})
city_score = city_score.rename(columns={'avg_time': 'city_avg_time'})
distance_score = distance_score.rename(columns={'avg_time': 'distance_avg_time'})

In [132]:
recommendation_df = dp.merge(
    weather_score,
    on='Delivery_person_ID',
    how='left'
)

recommendation_df = recommendation_df.merge(
    traffic_score,
    on='Delivery_person_ID',
    how='left'
)

recommendation_df = recommendation_df.merge(
    festival_score,
    on='Delivery_person_ID',
    how='left'
)

recommendation_df = recommendation_df.merge(
    city_score,
    on='Delivery_person_ID',
    how='left'
)

recommendation_df = recommendation_df.merge(
    distance_score,
    on='Delivery_person_ID',
    how='left'
)

In [134]:
recommendation_df['total_avg_time'] = recommendation_df[
    [
        'weather_avg_time',
        'traffic_avg_time',
        'festival_avg_time',
        'city_avg_time',
        'distance_avg_time'
    ]
].mean(axis=1)
recommendation_df.head()

,Delivery_person_ID,orders_completed,avg_deliverer_rating,avg_delivery_time,Weather_conditions,weather_avg_time,Road_traffic_density,traffic_avg_time,Festival,festival_avg_time,City,city_avg_time,distance_class,distance_avg_time,total_avg_time
0,AGRRES010DEL01,13,4.77,25.23,Cloudy,25.2,Low,23.67,No,25.23,Urban,29.50,0-5,23.00,25.320
1,AGRRES010DEL02,14,4.67,28.36,Cloudy,18.0,Low,19.60,No,26.92,Urban,26.75,0-5,22.75,22.804
2,AGRRES010DEL03,12,4.58,28.42,Cloudy,30.0,Low,16.75,No,26.64,Urban,15.00,0-5,32.50,24.178
3,AGRRES01DEL01,10,4.52,27.10,Cloudy,17.0,Low,14.50,No,27.10,Urban,12.00,0-5,17.00,17.520
4,AGRRES01DEL02,14,4.70,24.43,Cloudy,34.5,Low,17.67,No,24.43,Urban,17.00,0-5,15.67,21.854

In [154]:
# this is for sorting based on driver score; mostly for backend

def recommendation(weather, traffic, festival, city, distance):

    # Select scores based on input
    weather_score = weather_performance[
        weather_performance['Weather_conditions'] == weather
    ].copy()

    traffic_score = traffic_performance[
        traffic_performance['Road_traffic_density'] == traffic
    ].copy()

    festival_score = festival_performance[
        festival_performance['Festival'] == festival
    ].copy()

    city_score = city_performance[
        city_performance['City'] == city
    ].copy()

    distance_class = get_distance_class(distance)

    distance_score = distance_performance[
        distance_performance['distance_class'] == distance_class
    ].copy()

    # Rename average-time columns
    weather_score = weather_score.rename(
        columns={'avg_time': 'weather_avg_time'}
    )

    traffic_score = traffic_score.rename(
        columns={'avg_time': 'traffic_avg_time'}
    )

    festival_score = festival_score.rename(
        columns={'avg_time': 'festival_avg_time'}
    )

    city_score = city_score.rename(
        columns={'avg_time': 'city_avg_time'}
    )

    distance_score = distance_score.rename(
        columns={'avg_time': 'distance_avg_time'}
    )

    # Merge all scores
    recommendation_df = dp.merge(
        weather_score,
        on='Delivery_person_ID',
        how='left'
    )

    recommendation_df = recommendation_df.merge(
        traffic_score,
        on='Delivery_person_ID',
        how='left'
    )

    recommendation_df = recommendation_df.merge(
        festival_score,
        on='Delivery_person_ID',
        how='left'
    )

    recommendation_df = recommendation_df.merge(
        city_score,
        on='Delivery_person_ID',
        how='left'
    )

    recommendation_df = recommendation_df.merge(
        distance_score,
        on='Delivery_person_ID',
        how='left'
    )

    # Condition-specific average delivery time
    score_columns = [
        'weather_avg_time',
        'traffic_avg_time',
        'festival_avg_time',
        'city_avg_time',
        'distance_avg_time'
    ]

    recommendation_df['total_avg_time'] = recommendation_df[
        score_columns
    ].mean(axis=1)

    # Count missing scores
    recommendation_df['nan_count'] = recommendation_df[
        score_columns
    ].isna().sum(axis=1)

    # Normalize rating
    recommendation_df['rating_score'] = (
        recommendation_df['avg_deliverer_rating']
        - recommendation_df['avg_deliverer_rating'].min()
    ) / (
        recommendation_df['avg_deliverer_rating'].max()
        - recommendation_df['avg_deliverer_rating'].min()
    )

    # Normalize orders
    recommendation_df['orders_score'] = (
        recommendation_df['orders_completed']
        - recommendation_df['orders_completed'].min()
    ) / (
        recommendation_df['orders_completed'].max()
        - recommendation_df['orders_completed'].min()
    )

    # Normalize delivery time
    recommendation_df['time_score'] = (
        recommendation_df['total_avg_time'].max()
        - recommendation_df['total_avg_time']
    ) / (
        recommendation_df['total_avg_time'].max()
        - recommendation_df['total_avg_time'].min()
    )

    # Combined score
    recommendation_df['driver_score'] = (
        0.30 * recommendation_df['rating_score']
        + 0.20 * recommendation_df['orders_score']
        + 0.50 * recommendation_df['time_score']
    )

    # Sort first by least NaNs then by higher combined driver score
    recommendation_df = recommendation_df.sort_values(
        ['nan_count', 'driver_score'],
        ascending=[True, False]
    )

    # Keep only 4 unique delivery persons
    recommendation_df = recommendation_df.drop_duplicates(
        'Delivery_person_ID'
    ).head(4)

    return recommendation_df

In [155]:
recommendation(
    weather='Sunny',
    traffic='Low',
    festival='Yes',
    city='Urban',
    distance= 4 
)

,Delivery_person_ID,orders_completed,avg_deliverer_rating,avg_delivery_time,Weather_conditions,weather_avg_time,Road_traffic_density,traffic_avg_time,Festival,festival_avg_time,City,city_avg_time,distance_class,distance_avg_time,total_avg_time,nan_count,rating_score,orders_score,time_score,driver_score
927,MYSRES04DEL01,58,4.68,24.45,Sunny,16.86,Low,21.60,Yes,43.0,Urban,17.58,0-5,19.12,23.632,0,0.647059,0.900000,0.601664,0.674950
570,JAPRES01DEL01,51,4.69,25.61,Sunny,17.73,Low,18.43,Yes,39.0,Urban,20.50,0-5,20.62,23.256,0,0.661765,0.783333,0.616384,0.663388
928,MYSRES04DEL02,61,4.70,25.43,Sunny,22.10,Low,21.53,Yes,40.0,Urban,19.30,0-5,23.62,25.310,0,0.676471,0.950000,0.535969,0.660926
1119,SURRES14DEL01,55,4.69,25.36,Sunny,16.14,Low,19.36,Yes,49.5,Urban,19.27,0-5,17.27,24.308,0,0.661765,0.850000,0.575198,0.656129

In [156]:
def customer_recommendation(recommendation_df):

    df = recommendation_df.drop_duplicates(
        'Delivery_person_ID'
    ).copy()

    selected = []

    # with highest rating
    option_1 = df.sort_values(
        'avg_deliverer_rating',
        ascending=False
    ).iloc[0]

    selected.append(option_1['Delivery_person_ID'])

    # fastest driver
    option_2 = df[
        ~df['Delivery_person_ID'].isin(selected)
    ].sort_values(
        'total_avg_time',
        ascending=True
    ).iloc[0]

    selected.append(option_2['Delivery_person_ID'])

    # highest order counts
    option_3 = df[
        ~df['Delivery_person_ID'].isin(selected)
    ].sort_values(
        'orders_completed',
        ascending=False
    ).iloc[0]

    selected.append(option_3['Delivery_person_ID'])

    # balanced queen
    remaining = df[
        ~df['Delivery_person_ID'].isin(selected)
    ].copy()

    # normalize the three factors
    remaining['rating_score'] = (
        remaining['avg_deliverer_rating']
        - df['avg_deliverer_rating'].min()
    ) / (
        df['avg_deliverer_rating'].max()
        - df['avg_deliverer_rating'].min()
    )

    remaining['order_score'] = (
        remaining['orders_completed']
        - df['orders_completed'].min()
    ) / (
        df['orders_completed'].max()
        - df['orders_completed'].min()
    )

    remaining['time_score'] = (
        df['total_avg_time'].max()
        - remaining['total_avg_time']
    ) / (
        df['total_avg_time'].max()
        - df['total_avg_time'].min()
    )

    # equal importance to all three
    remaining['balance_score'] = (
        0.33 * remaining['rating_score']
        + 0.33 * remaining['order_score']
        + 0.34 * remaining['time_score']
    )

    option_4 = remaining.sort_values(
        'balance_score',
        ascending=False
    ).iloc[0]

    # Combining all 4 options
    customer_df = pd.DataFrame([
        option_1,
        option_2,
        option_3,
        option_4
    ])

    # keeping only what the customer needs to see
    customer_df = customer_df[
        [
            'Delivery_person_ID',
            'avg_deliverer_rating',
            'orders_completed',
            'total_avg_time'
        ]
    ]

    # Renaming for aesthetics hehe
    customer_df = customer_df.rename(
        columns={
            'Delivery_person_ID': 'Delivery Person',
            'avg_deliverer_rating': 'Rating',
            'orders_completed': 'Order Count',
            'total_avg_time': 'Avg Delivery Time'
        }
    )

    return customer_df

In [157]:
detailed_result = recommendation(
    weather='Sunny',
    traffic='High',
    festival='Yes',
    city='Urban',
    distance=16
)

customer_result = customer_recommendation(detailed_result)

customer_result

    Delivery Person  Rating  Order Count  Avg Delivery Time
927   MYSRES04DEL01    4.68           58             27.354
604   JAPRES13DEL02    4.67           51             25.186
540  INDORES12DEL01    4.67           59             27.166
555  INDORES17DEL01    4.67           54             25.908